//go:build go1.26 && goexperiment.simd && amd64

// simd_asm.go - used to check what assembler is generated by SIMD function calls

package main

import (
	"math"
	"simd/archsimd"
)

// $ go version   # go1.26
// $ cd main
// $ GOEXPERIMENT=simd go build simd_asm.go
// $ objdump -d simd_asm.exe > s.asm

// Notes
// %rip = instruction pointer
// %rsp = stack pointer
// %rcx = CX register
// XMM0 - XMM7 = 128bit (16 byte) registers - AVX?
// YMM0 - YMM15 = 256bit (32 byte) registers - AVX2

/*
func main() {
	//140079eb4:	c5 fe 6f 44 24 20    	vmovdqu 0x20(%rsp),%ymm0
	aVec32 := archsimd.LoadInt8x32(&[32]int8{1, 2, 3, 4, 5, 6, 7, 8, 9})

	//140079eba:	c4 e2 7d 1c c0       	vpabsb %ymm0,%ymm0
	result := aVec32.Abs()
}
*/

/*
func main() {
	v := archsimd.LoadInt8x32(&[32]int8{127, 0, -1, -127, -128})

	// Compare v to itself returns a mask (Mask8x32) of all true
	r := v.Equal(v) // VPCMPEQB
	//    140079eba:	c5 fd 74 c8          	vpcmpeqb %ymm0,%ymm0,%ymm1

	println(r.ToBits())

	vTrue := r.ToInt8x32()
	println(vTrue.String())

	// Not == XOR with true
	vNot := v.Xor(vTrue) // VPXOR
	//   140079ebe:	c5 fd ef c1          	vpxor  %ymm1,%ymm0,%ymm0

	println(vNot.String())
}
*/

func main() {
	v := archsimd.LoadInt64x4(&[4]int64{math.MaxInt64, 0, -1, math.MinInt64})
	r := v.Equal(v) // VPCMPEQQ
	// 140079f0d:	c4 e2 7d 29 c8       	vpcmpeqq %ymm0,%ymm0,%ymm1

	vTrue := r.ToInt64x4()
	vNot := v.Xor(vTrue) // VPXOR
	// c5 fd ef c1          	vpxor  %ymm1,%ymm0,%ymm0

	println(vNot.String())
}
