// Code generated by "stringer -type=MyEnum"; DO NOT EDIT.

package __

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Zero-0]
	_ = x[One-1]
	_ = x[Two-2]
	_ = x[Three-3]
	_ = x[MyEnumLast-4]
	_ = x[Uno-1]
}

const _MyEnum_name = "ZeroOneTwoThreeMyEnumLast"

var _MyEnum_index = [...]uint8{0, 4, 7, 10, 15, 25}

func (i MyEnum) String() string {
	if i >= MyEnum(len(_MyEnum_index)-1) {
		return "MyEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MyEnum_name[_MyEnum_index[i]:_MyEnum_index[i+1]]
}
